<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SellerInventoryItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $customer_unique_id = '3fc9290f-9810-4f63-b4d3-98ce481a5278';
        $marketplace_id = 1; // Assuming marketplace_id is constant

        $devices = [
            [
                'date' => '2024-06-03',
                'fnsku' => 'POS0001',
                'asin' => 'B000POS001',
                'msku' => 'NEXIPOS-001',
                'title' => 'Nexi POS Device Model X1',
                'disposition' => 'SELLABLE',
                'starting_warehouse_balance' => 10,
                'in_transit_between_warehouses' => 0,
                'receipts' => 0,
                'customer_shipments' => 2,
                'customer_returns' => 1,
                'vendor_returns' => 0,
                'warehouse_transfer_in_out' => 0,
                'found' => 0,
                'lost' => 0,
                'damaged' => 0,
                'disposed' => 0,
                'other_events' => 0,
                'ending_warehouse_balance' => 9,
                'unknown_events' => 0,
                'location' => 'IT',
                'customer_unique_id' => $customer_unique_id,
                'marketplace_id' => $marketplace_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'date' => '2024-06-03',
                'fnsku' => 'POS0002',
                'asin' => 'B000POS002',
                'msku' => 'NEXIPOS-002',
                'title' => 'Nexi POS Device Model X2',
                'disposition' => 'SELLABLE',
                'starting_warehouse_balance' => 5,
                'in_transit_between_warehouses' => 0,
                'receipts' => 0,
                'customer_shipments' => 1,
                'customer_returns' => 0,
                'vendor_returns' => 0,
                'warehouse_transfer_in_out' => 0,
                'found' => 0,
                'lost' => 0,
                'damaged' => 0,
                'disposed' => 0,
                'other_events' => 0,
                'ending_warehouse_balance' => 4,
                'unknown_events' => 0,
                'location' => 'IT',
                'customer_unique_id' => $customer_unique_id,
                'marketplace_id' => $marketplace_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'date' => '2024-06-03',
                'fnsku' => 'POS0011',
                'asin' => 'B000POS011',
                'msku' => 'NEXIPOS-011',
                'title' => 'Nexi POS Device Model X11',
                'disposition' => 'SELLABLE',
                'starting_warehouse_balance' => 10,
                'in_transit_between_warehouses' => 0,
                'receipts' => 0,
                'customer_shipments' => 2,
                'customer_returns' => 1,
                'vendor_returns' => 0,
                'warehouse_transfer_in_out' => 0,
                'found' => 0,
                'lost' => 0,
                'damaged' => 0,
                'disposed' => 0,
                'other_events' => 0,
                'ending_warehouse_balance' => 9,
                'unknown_events' => 0,
                'location' => 'IT',
                'customer_unique_id' => $customer_unique_id,
                'marketplace_id' => $marketplace_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'date' => '2024-06-03',
                'fnsku' => 'POS0012',
                'asin' => 'B000POS012',
                'msku' => 'NEXIPOS-012',
                'title' => 'Nexi POS Device Model X12',
                'disposition' => 'SELLABLE',
                'starting_warehouse_balance' => 5,
                'in_transit_between_warehouses' => 0,
                'receipts' => 0,
                'customer_shipments' => 1,
                'customer_returns' => 0,
                'vendor_returns' => 0,
                'warehouse_transfer_in_out' => 0,
                'found' => 0,
                'lost' => 0,
                'damaged' => 0,
                'disposed' => 0,
                'other_events' => 0,
                'ending_warehouse_balance' => 4,
                'unknown_events' => 0,
                'location' => 'IT',
                'customer_unique_id' => $customer_unique_id,
                'marketplace_id' => $marketplace_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'date' => '2024-06-03',
                'fnsku' => 'POS0021',
                'asin' => 'B000POS021',
                'msku' => 'NEXIPOS-021',
                'title' => 'Nexi POS Device Model X21',
                'disposition' => 'SELLABLE',
                'starting_warehouse_balance' => 10,
                'in_transit_between_warehouses' => 0,
                'receipts' => 0,
                'customer_shipments' => 2,
                'customer_returns' => 1,
                'vendor_returns' => 0,
                'warehouse_transfer_in_out' => 0,
                'found' => 0,
                'lost' => 0,
                'damaged' => 0,
                'disposed' => 0,
                'other_events' => 0,
                'ending_warehouse_balance' => 9,
                'unknown_events' => 0,
                'location' => 'IT',
                'customer_unique_id' => $customer_unique_id,
                'marketplace_id' => $marketplace_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'date' => '2024-06-03',
                'fnsku' => 'POS0022',
                'asin' => 'B000POS022',
                'msku' => 'NEXIPOS-022',
                'title' => 'Nexi POS Device Model X22',
                'disposition' => 'SELLABLE',
                'starting_warehouse_balance' => 5,
                'in_transit_between_warehouses' => 0,
                'receipts' => 0,
                'customer_shipments' => 1,
                'customer_returns' => 0,
                'vendor_returns' => 0,
                'warehouse_transfer_in_out' => 0,
                'found' => 0,
                'lost' => 0,
                'damaged' => 0,
                'disposed' => 0,
                'other_events' => 0,
                'ending_warehouse_balance' => 4,
                'unknown_events' => 0,
                'location' => 'IT',
                'customer_unique_id' => $customer_unique_id,
                'marketplace_id' => $marketplace_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'date' => '2024-06-03',
                'fnsku' => 'POS0031',
                'asin' => 'B000POS031',
                'msku' => 'NEXIPOS-031',
                'title' => 'Nexi POS Device Model X31',
                'disposition' => 'SELLABLE',
                'starting_warehouse_balance' => 10,
                'in_transit_between_warehouses' => 0,
                'receipts' => 0,
                'customer_shipments' => 2,
                'customer_returns' => 1,
                'vendor_returns' => 0,
                'warehouse_transfer_in_out' => 0,
                'found' => 0,
                'lost' => 0,
                'damaged' => 0,
                'disposed' => 0,
                'other_events' => 0,
                'ending_warehouse_balance' => 9,
                'unknown_events' => 0,
                'location' => 'IT',
                'customer_unique_id' => $customer_unique_id,
                'marketplace_id' => $marketplace_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'date' => '2024-06-03',
                'fnsku' => 'POS0032',
                'asin' => 'B000POS032',
                'msku' => 'NEXIPOS-032',
                'title' => 'Nexi POS Device Model X32',
                'disposition' => 'SELLABLE',
                'starting_warehouse_balance' => 5,
                'in_transit_between_warehouses' => 0,
                'receipts' => 0,
                'customer_shipments' => 1,
                'customer_returns' => 0,
                'vendor_returns' => 0,
                'warehouse_transfer_in_out' => 0,
                'found' => 0,
                'lost' => 0,
                'damaged' => 0,
                'disposed' => 0,
                'other_events' => 0,
                'ending_warehouse_balance' => 4,
                'unknown_events' => 0,
                'location' => 'IT',
                'customer_unique_id' => $customer_unique_id,
                'marketplace_id' => $marketplace_id,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('seller_inventory_items')->insert($devices);
    }
}
